# The behavior of RuboCop can be controlled via the .rubocop.yml
# configuration file. It makes it possible to enable/disable
# certain cops (checks) and to alter their behavior if they accept
# any parameters. The file can be placed either in your home
# directory or in some project directory.
#
# RuboCop will start looking for the configuration file in the directory
# where the inspected file is and continue its way up to the root directory.
#
# See https://docs.rubocop.org/rubocop/configuration

# pasted from https://github.com/cul/rubocul/tree/main
inherit_gem:
  rubocul: rubocul_default.yml

Style/FrozenStringLiteralComment:
  Enabled: false

Rails/Output:
  Enabled: false

AllCops:
  TargetRubyVersion: 3.1.0  # Update to your version of ruby
  TargetRailsVersion: 7.0.1 # Update to your version of rails